name: flavors
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  go_router: ^14.2.7
  shared_preferences: ^2.3.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.5
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.2.3

flutter:
  uses-material-design: true
  generate: true

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:
      targets:
        - name: Runner
  flavors:
    student:
      app:
        name: "Kids App"
      android:
        applicationId: "com.example.kids"
      ios:
        bundleId: "com.example.kids"
    teacher:
      app:
        name: "Tutor App"
      android:
        applicationId: "com.example.tutor"
      ios:
        bundleId: "com.example.tutor"
