name: flavors
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.2
  go_router: ^16.1.0
  shared_preferences: ^2.3.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_flavorizr: ^2.2.3

flutter:
  uses-material-design: true
  generate: true

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:
      targets:
        - name: Runner
  flavors:
    student:
      app:
        name: "Kids App"
      android:
        applicationId: "com.example.kids"
      ios:
        bundleId: "com.example.kids"
    teacher:
      app:
        name: "Tutor App"
      android:
        applicationId: "com.example.tutor"
      ios:
        bundleId: "com.example.tutor"
